use minijinja::Environment;

use crate::{CodegenError, GeneratedFile};

// ── template (embedded as const &str) ─────────────────────────────────────────

const RUNTIME_TMPL: &str = r#"/* Generated by nexus-gen — DO NOT EDIT */
#include <grpc/grpc.h>
#include <grpc/credentials.h>
#include <grpc/byte_buffer.h>
#include <grpc/support/alloc.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <pthread.h>

#define NEXUS_GRPC_MAX_METHODS 16

typedef struct {
    void* registered_method;
    const void* cache_ptr;
    size_t cache_size;
    pthread_mutex_t* cache_mutex;
} _nexus_grpc_method;

static grpc_server* _nexus_grpc_server = NULL;
static grpc_completion_queue* _nexus_grpc_cq = NULL;
static pthread_t _nexus_grpc_thread;
static int _nexus_grpc_running = 0;
static int _nexus_grpc_refcount = 0;
static pthread_mutex_t _nexus_grpc_init_mutex = PTHREAD_MUTEX_INITIALIZER;

static _nexus_grpc_method _nexus_grpc_methods[NEXUS_GRPC_MAX_METHODS];
static int _nexus_grpc_method_count = 0;

/* Per-call state used when waiting for a registered call to arrive. */
typedef struct {
    grpc_call* call;
    grpc_call_details details;
    grpc_metadata_array request_metadata;
    int method_idx;
} _nexus_grpc_pending;

static _nexus_grpc_pending _nexus_grpc_pending_calls[NEXUS_GRPC_MAX_METHODS];

static void _nexus_grpc_reregister(int method_idx);

static void _nexus_grpc_handle_request(int method_idx) {
    _nexus_grpc_method* m = &_nexus_grpc_methods[method_idx];
    _nexus_grpc_pending* p = &_nexus_grpc_pending_calls[method_idx];

    /* Build response byte buffer from cached data. */
    pthread_mutex_lock(m->cache_mutex);
    grpc_slice response_slice = grpc_slice_from_copied_buffer(
        (const char*)m->cache_ptr, m->cache_size);
    pthread_mutex_unlock(m->cache_mutex);

    grpc_byte_buffer* response_buf = grpc_raw_byte_buffer_create(&response_slice, 1);
    grpc_slice_unref(response_slice);

    grpc_metadata_array trailing_metadata;
    grpc_metadata_array_init(&trailing_metadata);

    grpc_op ops[3];
    memset(ops, 0, sizeof(ops));

    ops[0].op = GRPC_OP_SEND_INITIAL_METADATA;
    ops[0].data.send_initial_metadata.count = 0;
    ops[0].data.send_initial_metadata.metadata = NULL;

    ops[1].op = GRPC_OP_SEND_MESSAGE;
    ops[1].data.send_message.send_message = response_buf;

    ops[2].op = GRPC_OP_SEND_STATUS_FROM_SERVER;
    ops[2].data.send_status_from_server.trailing_metadata_count = 0;
    ops[2].data.send_status_from_server.trailing_metadata = NULL;
    ops[2].data.send_status_from_server.status = GRPC_STATUS_OK;
    ops[2].data.send_status_from_server.status_details = NULL;

    /* Tag encodes method index for the response completion event. */
    grpc_call_start_batch(p->call, ops, 3,
                          (void*)(intptr_t)(method_idx + NEXUS_GRPC_MAX_METHODS),
                          NULL);

    grpc_byte_buffer_destroy(response_buf);
    grpc_metadata_array_destroy(&trailing_metadata);

    /* Clean up call resources and re-register for the next incoming call. */
    grpc_call_details_destroy(&p->details);
    grpc_metadata_array_destroy(&p->request_metadata);
    grpc_call_unref(p->call);
    p->call = NULL;

    _nexus_grpc_reregister(method_idx);
}

static void _nexus_grpc_reregister(int method_idx) {
    _nexus_grpc_pending* p = &_nexus_grpc_pending_calls[method_idx];
    grpc_call_details_init(&p->details);
    grpc_metadata_array_init(&p->request_metadata);
    p->call = NULL;
    p->method_idx = method_idx;

    grpc_server_request_registered_call(
        _nexus_grpc_server,
        _nexus_grpc_methods[method_idx].registered_method,
        &p->call,
        &p->details.deadline,
        &p->request_metadata,
        NULL, /* optional payload */
        _nexus_grpc_cq,
        _nexus_grpc_cq,
        (void*)(intptr_t)method_idx);
}

static void* _nexus_grpc_server_loop(void* arg) {
    (void)arg;
    gpr_timespec deadline;

    while (_nexus_grpc_running) {
        deadline = gpr_time_add(gpr_now(GPR_CLOCK_REALTIME),
                                gpr_time_from_millis(100, GPR_TIMESPAN));
        grpc_event ev = grpc_completion_queue_next(_nexus_grpc_cq, deadline, NULL);

        if (ev.type == GRPC_QUEUE_TIMEOUT) {
            continue;
        }
        if (ev.type == GRPC_QUEUE_SHUTDOWN) {
            break;
        }

        /* ev.type == GRPC_OP_COMPLETE */
        if (!ev.success) {
            continue;
        }

        int tag = (int)(intptr_t)ev.tag;

        if (tag >= 0 && tag < _nexus_grpc_method_count) {
            /* Incoming call arrived for method at index `tag`. */
            _nexus_grpc_handle_request(tag);
        }
        /* Tags >= NEXUS_GRPC_MAX_METHODS are response completions; ignore. */
    }
    return NULL;
}

int _nexus_grpc_start(const char* addr) {
    pthread_mutex_lock(&_nexus_grpc_init_mutex);
    _nexus_grpc_refcount++;
    if (_nexus_grpc_server) {
        pthread_mutex_unlock(&_nexus_grpc_init_mutex);
        return 0; /* already started */
    }

    grpc_init();
    _nexus_grpc_server = grpc_server_create(NULL, NULL);
    _nexus_grpc_cq = grpc_completion_queue_create_for_next(NULL);
    grpc_server_register_completion_queue(_nexus_grpc_server, _nexus_grpc_cq, NULL);

    grpc_server_credentials* creds = grpc_insecure_server_credentials_create();
    int port = grpc_server_add_http2_port(_nexus_grpc_server, addr, creds);
    grpc_server_credentials_release(creds);

    if (port == 0) {
        grpc_server_destroy(_nexus_grpc_server);
        grpc_completion_queue_destroy(_nexus_grpc_cq);
        _nexus_grpc_server = NULL;
        _nexus_grpc_cq = NULL;
        _nexus_grpc_refcount--;
        pthread_mutex_unlock(&_nexus_grpc_init_mutex);
        return -1;
    }

    grpc_server_start(_nexus_grpc_server);
    _nexus_grpc_running = 1;
    pthread_create(&_nexus_grpc_thread, NULL, _nexus_grpc_server_loop, NULL);

    pthread_mutex_unlock(&_nexus_grpc_init_mutex);
    return 0;
}

int _nexus_grpc_register(const char* method_path, const void* cache_ptr,
                          size_t cache_size, pthread_mutex_t* cache_mutex) {
    if (!_nexus_grpc_server) return -1;
    if (_nexus_grpc_method_count >= NEXUS_GRPC_MAX_METHODS) return -1;

    int idx = _nexus_grpc_method_count++;
    _nexus_grpc_methods[idx].registered_method =
        grpc_server_register_method(_nexus_grpc_server, method_path, NULL,
                                     GRPC_SRM_PAYLOAD_NONE, 0);
    _nexus_grpc_methods[idx].cache_ptr = cache_ptr;
    _nexus_grpc_methods[idx].cache_size = cache_size;
    _nexus_grpc_methods[idx].cache_mutex = cache_mutex;

    /* Start accepting the first call for this method. */
    _nexus_grpc_reregister(idx);

    return idx;
}

void _nexus_grpc_stop(void) {
    pthread_mutex_lock(&_nexus_grpc_init_mutex);
    _nexus_grpc_refcount--;
    if (_nexus_grpc_refcount > 0 || !_nexus_grpc_server) {
        pthread_mutex_unlock(&_nexus_grpc_init_mutex);
        return;
    }

    _nexus_grpc_running = 0;
    grpc_server_shutdown_and_notify(_nexus_grpc_server, _nexus_grpc_cq, NULL);
    pthread_join(_nexus_grpc_thread, NULL);

    grpc_completion_queue_shutdown(_nexus_grpc_cq);

    /* Drain remaining events after shutdown. */
    gpr_timespec deadline = gpr_inf_future(GPR_CLOCK_REALTIME);
    grpc_event ev;
    do {
        ev = grpc_completion_queue_next(_nexus_grpc_cq, deadline, NULL);
    } while (ev.type != GRPC_QUEUE_SHUTDOWN);

    grpc_server_destroy(_nexus_grpc_server);
    grpc_completion_queue_destroy(_nexus_grpc_cq);
    _nexus_grpc_server = NULL;
    _nexus_grpc_cq = NULL;
    _nexus_grpc_method_count = 0;

    grpc_shutdown();
    pthread_mutex_unlock(&_nexus_grpc_init_mutex);
}
"#;

// ── public API ────────────────────────────────────────────────────────────────

/// Generate the shared gRPC server runtime file.
/// This file is node-independent infrastructure: one per node, not per contract.
pub fn generate_runtime() -> Result<GeneratedFile, CodegenError> {
    let mut env = Environment::new();
    env.add_template("runtime", RUNTIME_TMPL)?;
    let tmpl = env.get_template("runtime")?;

    // No template variables — the runtime is fully static.
    let rendered = tmpl.render(minijinja::context! {})?;

    Ok(GeneratedFile {
        path: "src/nexus_grpc_runtime.c".to_string(),
        content: rendered,
    })
}

// ── tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_runtime_generation() {
        let file = generate_runtime().unwrap();
        assert_eq!(file.path, "src/nexus_grpc_runtime.c");
        assert!(file.content.contains("_nexus_grpc_start"));
        assert!(file.content.contains("_nexus_grpc_stop"));
        assert!(file.content.contains("_nexus_grpc_register"));
        assert!(file.content.contains("grpc_server_create"));
        assert!(file.content.contains("pthread_create"));
    }
}
