use minijinja::{context, Environment, Value};
use nexus_core::{Contract, FieldType, Node, Schema, StructDef};

use crate::{CodegenError, GeneratedFile};

// ── templates (embedded as const &str) ────────────────────────────────────────

const HEADER_TMPL: &str = r#"/* Generated by nexus-gen — DO NOT EDIT */
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

/* Error codes */
#define NEXUS_OK            0
#define NEXUS_ERR_TIMEOUT  -1
#define NEXUS_ERR_CLOSED   -2
#define NEXUS_ERR_INIT     -3

{% for s in structs %}
typedef struct {
{% for field_decl in s.fields %}
    {{ field_decl }};
{% endfor %}
} Nexus{{ s.pascal_name }};
{% endfor %}

int  nexus_{{ contract_name }}_init(void);
void nexus_{{ contract_name }}_destroy(void);
int  nexus_send_{{ contract_name }}(const Nexus{{ top_struct_name }}* data);
int  nexus_recv_{{ contract_name }}(Nexus{{ top_struct_name }}* out);

#ifdef __cplusplus
}
#endif
"#;

const UMBRELLA_TMPL: &str = r#"/* Generated by nexus-gen — DO NOT EDIT */
/* Umbrella header for node: {{ node_name }} */
#pragma once

{% for contract_name in contract_names %}
#include "nexus_{{ contract_name }}.h"
{% endfor %}
"#;

// ── public API ────────────────────────────────────────────────────────────────

pub fn generate_header(
    contract: &Contract,
    schema: &Schema,
) -> Result<GeneratedFile, CodegenError> {
    let mut env = Environment::new();
    env.add_template("header", HEADER_TMPL)?;
    let tmpl = env.get_template("header")?;

    // Build struct list: [{pascal_name, fields: [decl_string]}]
    // schema.structs is assumed to be in dependency order (nested first).
    let structs: Vec<Value> = schema.structs.iter().map(struct_to_value).collect();

    let top_struct_name = to_pascal_case(&contract.name);

    let rendered = tmpl.render(context! {
        contract_name => contract.name,
        top_struct_name => top_struct_name,
        structs => structs,
    })?;

    Ok(GeneratedFile {
        path: format!("include/nexus_{}.h", contract.name),
        content: rendered,
    })
}

pub fn generate_umbrella(
    node: &Node,
    contracts: &[&Contract],
) -> Result<GeneratedFile, CodegenError> {
    let mut env = Environment::new();
    env.add_template("umbrella", UMBRELLA_TMPL)?;
    let tmpl = env.get_template("umbrella")?;

    let contract_names: Vec<&str> = contracts.iter().map(|c| c.name.as_str()).collect();

    let rendered = tmpl.render(context! {
        node_name => node.name,
        contract_names => contract_names,
    })?;

    Ok(GeneratedFile {
        path: format!("include/nexus_{}.h", node.name),
        content: rendered,
    })
}

// ── helpers ───────────────────────────────────────────────────────────────────

/// Convert snake_case to PascalCase: "game_info" -> "GameInfo".
pub fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

/// Map a FieldType to its C base type string (without array suffix).
pub fn field_type_to_c_base(typ: &FieldType) -> String {
    match typ {
        FieldType::U8 => "uint8_t".to_string(),
        FieldType::U16 => "uint16_t".to_string(),
        FieldType::U32 => "uint32_t".to_string(),
        FieldType::U64 => "uint64_t".to_string(),
        FieldType::I8 => "int8_t".to_string(),
        FieldType::I16 => "int16_t".to_string(),
        FieldType::I32 => "int32_t".to_string(),
        FieldType::I64 => "int64_t".to_string(),
        FieldType::F32 => "float".to_string(),
        FieldType::F64 => "double".to_string(),
        FieldType::Bool => "uint8_t".to_string(),
        FieldType::Bytes(_) => "uint8_t".to_string(),
        FieldType::StringFixed(_) => "char".to_string(),
        FieldType::Array { elem, .. } => field_type_to_c_base(elem),
        FieldType::Nested(name) => format!("Nexus{}", to_pascal_case(name)),
    }
}

/// Returns true for field types that generate array members.
pub fn is_array_field(typ: &FieldType) -> bool {
    matches!(
        typ,
        FieldType::Bytes(_) | FieldType::StringFixed(_) | FieldType::Array { .. }
    )
}

/// Build a complete C field declaration string, e.g. `uint8_t tags[8]`.
pub fn field_decl(field_name: &str, typ: &FieldType) -> String {
    match typ {
        FieldType::Bytes(n) => format!("uint8_t {}[{}]", field_name, n),
        FieldType::StringFixed(n) => format!("char {}[{}]", field_name, n),
        FieldType::Array { elem, len } => {
            format!("{} {}[{}]", field_type_to_c_base(elem), field_name, len)
        }
        other => format!("{} {}", field_type_to_c_base(other), field_name),
    }
}

/// Build a minijinja Value for a StructDef: {pascal_name, fields: [decl_string]}.
fn struct_to_value(s: &StructDef) -> Value {
    let pascal_name = to_pascal_case(&s.name);
    let fields: Vec<String> = s
        .fields
        .iter()
        .map(|f| field_decl(&f.name, &f.typ))
        .collect();

    context! {
        pascal_name => pascal_name,
        fields => fields,
    }
}

// ── tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use nexus_core::{Contract, Field, FieldType, Node, Schema, SchemaIdx, StructDef, Transport};

    use super::*;

    fn simple_contract() -> (Contract, Schema) {
        let contract = Contract {
            name: "game_info".to_string(),
            transport: Transport::UnixSocket,
            schema: SchemaIdx(0),
        };
        let schema = Schema {
            name: "game_info".to_string(),
            structs: vec![StructDef {
                name: "game_info".to_string(),
                fields: vec![
                    Field {
                        name: "player_id".to_string(),
                        typ: FieldType::U32,
                    },
                    Field {
                        name: "position_x".to_string(),
                        typ: FieldType::F32,
                    },
                    Field {
                        name: "timestamp".to_string(),
                        typ: FieldType::U64,
                    },
                ],
            }],
        };
        (contract, schema)
    }

    #[test]
    fn test_header_generation() {
        let (contract, schema) = simple_contract();
        let file = generate_header(&contract, &schema).unwrap();

        assert_eq!(file.path, "include/nexus_game_info.h");

        let c = &file.content;
        assert!(c.contains("#pragma once"), "missing #pragma once");
        assert!(c.contains("extern \"C\""), "missing extern C");
        assert!(c.contains("NEXUS_OK"), "missing NEXUS_OK");
        assert!(c.contains("NEXUS_ERR_INIT"), "missing NEXUS_ERR_INIT");
        assert!(c.contains("typedef struct"), "missing typedef struct");
        assert!(c.contains("NexusGameInfo"), "missing struct name");
        assert!(c.contains("uint32_t player_id"), "missing player_id field");
        assert!(c.contains("float position_x"), "missing position_x field");
        assert!(c.contains("uint64_t timestamp"), "missing timestamp field");
        assert!(c.contains("nexus_game_info_init"), "missing init function");
        assert!(
            c.contains("nexus_game_info_destroy"),
            "missing destroy function"
        );
        assert!(c.contains("nexus_send_game_info"), "missing send function");
        assert!(c.contains("nexus_recv_game_info"), "missing recv function");
        assert!(
            c.contains("#include <stdint.h>"),
            "missing stdint.h include"
        );
    }

    #[test]
    fn test_header_nested_struct() {
        let contract = Contract {
            name: "player_state".to_string(),
            transport: Transport::UnixSocket,
            schema: SchemaIdx(0),
        };
        // Two structs: Vector2 (nested) then PlayerState (parent)
        let schema = Schema {
            name: "player_state".to_string(),
            structs: vec![
                StructDef {
                    name: "vector2".to_string(),
                    fields: vec![
                        Field {
                            name: "x".to_string(),
                            typ: FieldType::F32,
                        },
                        Field {
                            name: "y".to_string(),
                            typ: FieldType::F32,
                        },
                    ],
                },
                StructDef {
                    name: "player_state".to_string(),
                    fields: vec![
                        Field {
                            name: "pos".to_string(),
                            typ: FieldType::Nested("vector2".to_string()),
                        },
                        Field {
                            name: "health".to_string(),
                            typ: FieldType::U32,
                        },
                    ],
                },
            ],
        };

        let file = generate_header(&contract, &schema).unwrap();
        let c = &file.content;

        // NexusVector2 must appear before NexusPlayerState
        let pos_vector2 = c.find("NexusVector2").expect("NexusVector2 missing");
        let pos_player = c
            .find("NexusPlayerState")
            .expect("NexusPlayerState missing");
        assert!(
            pos_vector2 < pos_player,
            "nested struct must appear before parent"
        );
    }

    #[test]
    fn test_header_array_field() {
        let contract = Contract {
            name: "tagged_event".to_string(),
            transport: Transport::UnixSocket,
            schema: SchemaIdx(0),
        };
        let schema = Schema {
            name: "tagged_event".to_string(),
            structs: vec![StructDef {
                name: "tagged_event".to_string(),
                fields: vec![
                    Field {
                        name: "id".to_string(),
                        typ: FieldType::U32,
                    },
                    Field {
                        name: "tags".to_string(),
                        typ: FieldType::Bytes(8),
                    },
                ],
            }],
        };

        let file = generate_header(&contract, &schema).unwrap();
        assert!(
            file.content.contains("uint8_t tags[8]"),
            "expected array field declaration"
        );
    }

    #[test]
    fn test_umbrella_header() {
        let node = Node {
            name: "backend".to_string(),
        };
        let c1 = Contract {
            name: "game_info".to_string(),
            transport: Transport::UnixSocket,
            schema: SchemaIdx(0),
        };
        let c2 = Contract {
            name: "display".to_string(),
            transport: Transport::UnixSocket,
            schema: SchemaIdx(1),
        };

        let file = generate_umbrella(&node, &[&c1, &c2]).unwrap();

        assert_eq!(file.path, "include/nexus_backend.h");
        let c = &file.content;
        assert!(c.contains("#pragma once"), "missing #pragma once");
        assert!(c.contains("nexus_game_info.h"), "missing game_info include");
        assert!(c.contains("nexus_display.h"), "missing display include");
        assert!(c.contains("backend"), "missing node name");
    }

    #[test]
    fn test_type_mapping() {
        // Exhaustive check of every FieldType variant
        assert_eq!(field_type_to_c_base(&FieldType::U8), "uint8_t");
        assert_eq!(field_type_to_c_base(&FieldType::U16), "uint16_t");
        assert_eq!(field_type_to_c_base(&FieldType::U32), "uint32_t");
        assert_eq!(field_type_to_c_base(&FieldType::U64), "uint64_t");
        assert_eq!(field_type_to_c_base(&FieldType::I8), "int8_t");
        assert_eq!(field_type_to_c_base(&FieldType::I16), "int16_t");
        assert_eq!(field_type_to_c_base(&FieldType::I32), "int32_t");
        assert_eq!(field_type_to_c_base(&FieldType::I64), "int64_t");
        assert_eq!(field_type_to_c_base(&FieldType::F32), "float");
        assert_eq!(field_type_to_c_base(&FieldType::F64), "double");
        assert_eq!(field_type_to_c_base(&FieldType::Bool), "uint8_t");
        assert_eq!(field_type_to_c_base(&FieldType::Bytes(4)), "uint8_t");
        assert_eq!(field_type_to_c_base(&FieldType::StringFixed(16)), "char");
        assert_eq!(
            field_type_to_c_base(&FieldType::Array {
                elem: Box::new(FieldType::U16),
                len: 3,
            }),
            "uint16_t"
        );
        assert_eq!(
            field_type_to_c_base(&FieldType::Nested("my_type".to_string())),
            "NexusMyType"
        );

        // is_array_field
        assert!(is_array_field(&FieldType::Bytes(1)));
        assert!(is_array_field(&FieldType::StringFixed(1)));
        assert!(is_array_field(&FieldType::Array {
            elem: Box::new(FieldType::U8),
            len: 1
        }));
        assert!(!is_array_field(&FieldType::U32));
        assert!(!is_array_field(&FieldType::Nested("x".to_string())));
    }

    #[test]
    fn test_pascal_case() {
        assert_eq!(to_pascal_case("game_info"), "GameInfo");
        assert_eq!(to_pascal_case("a"), "A");
        assert_eq!(to_pascal_case("hello_world"), "HelloWorld");
        assert_eq!(to_pascal_case("foo"), "Foo");
        assert_eq!(to_pascal_case("already_pascal"), "AlreadyPascal");
    }
}
