use minijinja::Environment;

use crate::{CodegenError, GeneratedFile};

// ── template (embedded as const &str) ─────────────────────────────────────────

const RUNTIME_TMPL: &str = r#"/* Generated by nexus-gen — DO NOT EDIT */
#include <microhttpd.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <pthread.h>

#define NEXUS_HTTP_MAX_ROUTES 16

typedef char* (*_nexus_json_fn)(const void* data);

typedef struct {
    const char* path;
    const void* cache_ptr;
    pthread_mutex_t* cache_mutex;
    _nexus_json_fn to_json;
} _nexus_http_route;

static struct MHD_Daemon* _nexus_http_daemon = NULL;
static int _nexus_http_refcount = 0;
static pthread_mutex_t _nexus_http_init_mutex = PTHREAD_MUTEX_INITIALIZER;

static _nexus_http_route _nexus_http_routes[NEXUS_HTTP_MAX_ROUTES];
static int _nexus_http_route_count = 0;

static enum MHD_Result _nexus_http_handler(
    void* cls,
    struct MHD_Connection* connection,
    const char* url,
    const char* method,
    const char* version,
    const char* upload_data,
    size_t* upload_data_size,
    void** con_cls)
{
    (void)cls; (void)version; (void)upload_data; (void)upload_data_size; (void)con_cls;

    if (strcmp(method, "GET") != 0) {
        struct MHD_Response* response = MHD_create_response_from_buffer(
            0, NULL, MHD_RESPMEM_PERSISTENT);
        enum MHD_Result ret = MHD_queue_response(connection, MHD_HTTP_METHOD_NOT_ALLOWED, response);
        MHD_destroy_response(response);
        return ret;
    }

    /* Match route */
    for (int i = 0; i < _nexus_http_route_count; i++) {
        if (strcmp(url, _nexus_http_routes[i].path) == 0) {
            _nexus_http_route* r = &_nexus_http_routes[i];

            pthread_mutex_lock(r->cache_mutex);
            char* json = r->to_json(r->cache_ptr);
            pthread_mutex_unlock(r->cache_mutex);

            if (!json) {
                const char* err = "{\"error\":\"serialization failed\"}";
                struct MHD_Response* response = MHD_create_response_from_buffer(
                    strlen(err), (void*)err, MHD_RESPMEM_PERSISTENT);
                MHD_add_response_header(response, "Content-Type", "application/json");
                enum MHD_Result ret = MHD_queue_response(connection, MHD_HTTP_INTERNAL_SERVER_ERROR, response);
                MHD_destroy_response(response);
                return ret;
            }

            struct MHD_Response* response = MHD_create_response_from_buffer(
                strlen(json), json, MHD_RESPMEM_MUST_FREE);
            MHD_add_response_header(response, "Content-Type", "application/json");
            MHD_add_response_header(response, "Access-Control-Allow-Origin", "*");
            enum MHD_Result ret = MHD_queue_response(connection, MHD_HTTP_OK, response);
            MHD_destroy_response(response);
            return ret;
        }
    }

    /* 404 for unknown routes */
    const char* not_found = "{\"error\":\"not found\"}";
    struct MHD_Response* response = MHD_create_response_from_buffer(
        strlen(not_found), (void*)not_found, MHD_RESPMEM_PERSISTENT);
    MHD_add_response_header(response, "Content-Type", "application/json");
    enum MHD_Result ret = MHD_queue_response(connection, MHD_HTTP_NOT_FOUND, response);
    MHD_destroy_response(response);
    return ret;
}

int _nexus_http_start(int port) {
    pthread_mutex_lock(&_nexus_http_init_mutex);
    _nexus_http_refcount++;
    if (_nexus_http_daemon) {
        pthread_mutex_unlock(&_nexus_http_init_mutex);
        return 0; /* already started */
    }

    _nexus_http_daemon = MHD_start_daemon(
        MHD_USE_INTERNAL_POLLING_THREAD,
        (uint16_t)port,
        NULL, NULL,
        &_nexus_http_handler, NULL,
        MHD_OPTION_END);

    if (!_nexus_http_daemon) {
        _nexus_http_refcount--;
        pthread_mutex_unlock(&_nexus_http_init_mutex);
        return -1;
    }

    pthread_mutex_unlock(&_nexus_http_init_mutex);
    return 0;
}

int _nexus_http_register(const char* path, const void* cache_ptr,
                          pthread_mutex_t* cache_mutex, _nexus_json_fn to_json) {
    if (_nexus_http_route_count >= NEXUS_HTTP_MAX_ROUTES) return -1;

    int idx = _nexus_http_route_count++;
    _nexus_http_routes[idx].path = path;
    _nexus_http_routes[idx].cache_ptr = cache_ptr;
    _nexus_http_routes[idx].cache_mutex = cache_mutex;
    _nexus_http_routes[idx].to_json = to_json;

    return idx;
}

void _nexus_http_stop(void) {
    pthread_mutex_lock(&_nexus_http_init_mutex);
    _nexus_http_refcount--;
    if (_nexus_http_refcount > 0 || !_nexus_http_daemon) {
        pthread_mutex_unlock(&_nexus_http_init_mutex);
        return;
    }

    MHD_stop_daemon(_nexus_http_daemon);
    _nexus_http_daemon = NULL;
    _nexus_http_route_count = 0;

    pthread_mutex_unlock(&_nexus_http_init_mutex);
}
"#;

// ── public API ────────────────────────────────────────────────────────────────

/// Generate the shared HTTP server runtime file (libmicrohttpd-based).
/// This file is node-independent and contains no template variables.
/// One copy per node output directory is sufficient.
///
/// The `_contract` and `_schema` parameters are accepted for API symmetry
/// but are not used — the runtime is contract-agnostic.
pub fn generate_runtime() -> Result<GeneratedFile, CodegenError> {
    let mut env = Environment::new();
    env.add_template("runtime", RUNTIME_TMPL)?;
    let tmpl = env.get_template("runtime")?;

    let rendered = tmpl.render(minijinja::context! {})?;

    Ok(GeneratedFile {
        path: "src/nexus_http_runtime.c".to_string(),
        content: rendered,
    })
}

// ── tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_runtime_generation() {
        let file = generate_runtime().unwrap();
        assert_eq!(file.path, "src/nexus_http_runtime.c");
        assert!(file.content.contains("_nexus_http_start"));
        assert!(file.content.contains("_nexus_http_stop"));
        assert!(file.content.contains("_nexus_http_register"));
        assert!(file.content.contains("MHD_start_daemon"));
        assert!(file.content.contains("MHD_stop_daemon"));
        assert!(file.content.contains("application/json"));
        assert!(file.content.contains("_nexus_json_fn"));
    }
}
