use minijinja::{context, Environment};
use nexus_core::{Contract, Schema};

use crate::{header::to_pascal_case, CodegenError, GeneratedFile};

// ── template (embedded as const &str) ─────────────────────────────────────────

const IMPL_TMPL: &str = r#"/* Generated by nexus-gen — DO NOT EDIT */
#include "nexus_{{ contract_name }}.h"
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <pthread.h>

/* Shared HTTP runtime (from nexus_http_runtime.c) */
extern int _nexus_http_start(int port);
extern int _nexus_http_register(const char* path, const void* cache_ptr,
                                 size_t cache_size, pthread_mutex_t* mutex);
extern void _nexus_http_stop(void);

static Nexus{{ struct_name }} _nexus_{{ contract_name }}_cache;
static pthread_mutex_t _nexus_{{ contract_name }}_mutex = PTHREAD_MUTEX_INITIALIZER;

int nexus_{{ contract_name }}_init(void) {
    const char* addr = getenv("NEXUS_{{ contract_name_upper }}_ADDR");
    int port = 8080;
    if (addr) {
        /* Parse port from URL like "http://0.0.0.0:8080/nexus/..." or just "8080" */
        const char* colon = strrchr(addr, ':');
        if (colon) {
            int p = atoi(colon + 1);
            if (p > 0) port = p;
        }
    }

    memset(&_nexus_{{ contract_name }}_cache, 0, sizeof(_nexus_{{ contract_name }}_cache));

    if (_nexus_http_start(port) != 0) return NEXUS_ERR_INIT;

    if (_nexus_http_register(
            "/nexus/{{ contract_name }}",
            &_nexus_{{ contract_name }}_cache,
            sizeof(_nexus_{{ contract_name }}_cache),
            &_nexus_{{ contract_name }}_mutex) < 0) {
        return NEXUS_ERR_INIT;
    }

    return NEXUS_OK;
}

void nexus_{{ contract_name }}_destroy(void) {
    _nexus_http_stop();
}

int nexus_send_{{ contract_name }}(const Nexus{{ struct_name }}* data) {
    pthread_mutex_lock(&_nexus_{{ contract_name }}_mutex);
    memcpy(&_nexus_{{ contract_name }}_cache, data, sizeof(*data));
    pthread_mutex_unlock(&_nexus_{{ contract_name }}_mutex);
    return NEXUS_OK;
}

int nexus_recv_{{ contract_name }}(Nexus{{ struct_name }}* out) {
    /* Server nodes do not receive on this contract */
    (void)out;
    return NEXUS_ERR_INIT;
}
"#;

// ── public API ────────────────────────────────────────────────────────────────

/// Generate a per-contract HTTP server handler file (libmicrohttpd-based).
/// The server caches the last value written via `nexus_send_*` and serves it
/// over HTTP GET at `/nexus/<contract_name>`.
pub fn generate_impl(contract: &Contract, schema: &Schema) -> Result<GeneratedFile, CodegenError> {
    let mut env = Environment::new();
    env.add_template("impl", IMPL_TMPL)?;
    let tmpl = env.get_template("impl")?;

    let contract_name_upper = contract.name.to_uppercase();
    let struct_name = schema.structs.last()
        .map(|s| to_pascal_case(&s.name))
        .unwrap_or_else(|| to_pascal_case(&contract.name));

    let rendered = tmpl.render(context! {
        contract_name => contract.name,
        contract_name_upper => contract_name_upper,
        struct_name => struct_name,
    })?;

    Ok(GeneratedFile {
        path: format!("src/nexus_{}_server.c", contract.name),
        content: rendered,
    })
}

// ── tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use nexus_core::{Contract, Schema, SchemaIdx, StructDef, Transport};

    use super::*;

    fn test_contract() -> (Contract, Schema) {
        let contract = Contract {
            name: "game_info".to_string(),
            transport: Transport::Http,
            schema: SchemaIdx(0),
        };
        let schema = Schema {
            name: "game_info".to_string(),
            structs: vec![StructDef {
                name: "game_info".to_string(),
                fields: vec![],
            }],
        };
        (contract, schema)
    }

    #[test]
    fn test_server_impl_generation() {
        let (contract, schema) = test_contract();
        let file = generate_impl(&contract, &schema).unwrap();
        assert_eq!(file.path, "src/nexus_game_info_server.c");
        assert!(file.content.contains("_nexus_http_start"));
        assert!(file.content.contains("_nexus_http_register"));
        assert!(file.content.contains("/nexus/game_info"));
        assert!(file.content.contains("nexus_send_game_info"));
        assert!(file.content.contains("pthread_mutex_lock"));
    }
}
