use minijinja::{context, Environment};
use nexus_core::{Contract, Schema};

use crate::{header::to_pascal_case, CodegenError, GeneratedFile};

// ── template (embedded as const &str) ─────────────────────────────────────────

const IMPL_TMPL: &str = r#"/* Generated by nexus-gen — DO NOT EDIT */
#include "nexus_{{ contract_name }}.h"
#include <curl/curl.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

static CURL* _nexus_{{ contract_name }}_curl = NULL;
static char _nexus_{{ contract_name }}_url[512];

static size_t _nexus_{{ contract_name }}_write_cb(void* ptr, size_t size, size_t nmemb, void* userdata) {
    size_t total = size * nmemb;
    Nexus{{ struct_name }}* out = (Nexus{{ struct_name }}*)userdata;
    if (total >= sizeof(*out)) {
        memcpy(out, ptr, sizeof(*out));
    }
    return total;
}

int nexus_{{ contract_name }}_init(void) {
    const char* addr = getenv("NEXUS_{{ contract_name_upper }}_ADDR");
    if (!addr) addr = "http://localhost:8080/nexus/{{ contract_name }}";
    strncpy(_nexus_{{ contract_name }}_url, addr, sizeof(_nexus_{{ contract_name }}_url) - 1);
    _nexus_{{ contract_name }}_url[sizeof(_nexus_{{ contract_name }}_url) - 1] = '\0';

    if (curl_global_init(CURL_GLOBAL_DEFAULT) != CURLE_OK) return NEXUS_ERR_INIT;

    _nexus_{{ contract_name }}_curl = curl_easy_init();
    if (!_nexus_{{ contract_name }}_curl) return NEXUS_ERR_INIT;

    return NEXUS_OK;
}

void nexus_{{ contract_name }}_destroy(void) {
    if (_nexus_{{ contract_name }}_curl) {
        curl_easy_cleanup(_nexus_{{ contract_name }}_curl);
        _nexus_{{ contract_name }}_curl = NULL;
    }
    curl_global_cleanup();
}

int nexus_send_{{ contract_name }}(const Nexus{{ struct_name }}* data) {
    if (!_nexus_{{ contract_name }}_curl) return NEXUS_ERR_CLOSED;

    curl_easy_setopt(_nexus_{{ contract_name }}_curl, CURLOPT_URL, _nexus_{{ contract_name }}_url);
    curl_easy_setopt(_nexus_{{ contract_name }}_curl, CURLOPT_POST, 1L);
    curl_easy_setopt(_nexus_{{ contract_name }}_curl, CURLOPT_POSTFIELDS, (const char*)data);
    curl_easy_setopt(_nexus_{{ contract_name }}_curl, CURLOPT_POSTFIELDSIZE, (long)sizeof(*data));

    struct curl_slist* headers = NULL;
    headers = curl_slist_append(headers, "Content-Type: application/octet-stream");
    curl_easy_setopt(_nexus_{{ contract_name }}_curl, CURLOPT_HTTPHEADER, headers);

    CURLcode res = curl_easy_perform(_nexus_{{ contract_name }}_curl);
    curl_slist_free_all(headers);

    if (res != CURLE_OK) return NEXUS_ERR_CLOSED;
    return NEXUS_OK;
}

int nexus_recv_{{ contract_name }}(Nexus{{ struct_name }}* out) {
    if (!_nexus_{{ contract_name }}_curl) return NEXUS_ERR_CLOSED;

    curl_easy_setopt(_nexus_{{ contract_name }}_curl, CURLOPT_URL, _nexus_{{ contract_name }}_url);
    curl_easy_setopt(_nexus_{{ contract_name }}_curl, CURLOPT_HTTPGET, 1L);
    curl_easy_setopt(_nexus_{{ contract_name }}_curl, CURLOPT_WRITEFUNCTION, _nexus_{{ contract_name }}_write_cb);
    curl_easy_setopt(_nexus_{{ contract_name }}_curl, CURLOPT_WRITEDATA, (void*)out);

    CURLcode res = curl_easy_perform(_nexus_{{ contract_name }}_curl);
    if (res != CURLE_OK) return NEXUS_ERR_CLOSED;
    return NEXUS_OK;
}
"#;

// ── public API ────────────────────────────────────────────────────────────────

/// Generate an HTTP/libcurl C implementation file for the given contract.
pub fn generate_impl(contract: &Contract, schema: &Schema) -> Result<GeneratedFile, CodegenError> {
    let mut env = Environment::new();
    env.add_template("impl", IMPL_TMPL)?;
    let tmpl = env.get_template("impl")?;

    let contract_name_upper = contract.name.to_uppercase();
    let struct_name = schema.structs.last()
        .map(|s| to_pascal_case(&s.name))
        .unwrap_or_else(|| to_pascal_case(&contract.name));

    let rendered = tmpl.render(context! {
        contract_name => contract.name,
        contract_name_upper => contract_name_upper,
        struct_name => struct_name,
    })?;

    Ok(GeneratedFile {
        path: format!("src/nexus_{}.c", contract.name),
        content: rendered,
    })
}

// ── tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use nexus_core::{Contract, Schema, SchemaIdx, StructDef, Transport};

    use super::*;

    fn test_contract() -> (Contract, Schema) {
        let contract = Contract {
            name: "game_info".to_string(),
            transport: Transport::Http,
            schema: SchemaIdx(0),
        };
        let schema = Schema {
            name: "game_info".to_string(),
            structs: vec![StructDef {
                name: "game_info".to_string(),
                fields: vec![],
            }],
        };
        (contract, schema)
    }

    #[test]
    fn test_impl_generation() {
        let (contract, schema) = test_contract();
        let file = generate_impl(&contract, &schema).unwrap();

        assert_eq!(file.path, "src/nexus_game_info.c");

        let c = &file.content;

        // Includes
        assert!(
            c.contains("#include \"nexus_game_info.h\""),
            "missing own header include"
        );
        assert!(
            c.contains("#include <curl/curl.h>"),
            "missing curl include"
        );
        assert!(c.contains("#include <stdlib.h>"), "missing stdlib include");
        assert!(c.contains("#include <string.h>"), "missing string include");
        assert!(c.contains("#include <stdio.h>"), "missing stdio include");

        // Static variables
        assert!(
            c.contains("static CURL* _nexus_game_info_curl = NULL;"),
            "missing static curl handle"
        );
        assert!(
            c.contains("static char _nexus_game_info_url[512];"),
            "missing static url buffer"
        );

        // Write callback
        assert!(
            c.contains("_nexus_game_info_write_cb"),
            "missing write callback"
        );

        // Functions
        assert!(c.contains("nexus_game_info_init"), "missing init function");
        assert!(
            c.contains("nexus_game_info_destroy"),
            "missing destroy function"
        );
        assert!(c.contains("nexus_send_game_info"), "missing send function");
        assert!(c.contains("nexus_recv_game_info"), "missing recv function");

        // Struct name
        assert!(
            c.contains("NexusGameInfo"),
            "missing struct name in functions"
        );

        // Env var name
        assert!(c.contains("NEXUS_GAME_INFO_ADDR"), "missing env var");

        // Default URL
        assert!(
            c.contains("http://localhost:8080/nexus/game_info"),
            "missing default URL"
        );

        // curl API usage
        assert!(
            c.contains("curl_global_init(CURL_GLOBAL_DEFAULT)"),
            "missing curl_global_init"
        );
        assert!(
            c.contains("curl_easy_init()"),
            "missing curl_easy_init"
        );
        assert!(
            c.contains("curl_easy_cleanup"),
            "missing curl_easy_cleanup"
        );
        assert!(
            c.contains("curl_global_cleanup"),
            "missing curl_global_cleanup"
        );
        assert!(
            c.contains("CURLOPT_POSTFIELDS"),
            "missing CURLOPT_POSTFIELDS"
        );
        assert!(
            c.contains("CURLOPT_POSTFIELDSIZE"),
            "missing CURLOPT_POSTFIELDSIZE"
        );
        assert!(
            c.contains("Content-Type: application/octet-stream"),
            "missing Content-Type header"
        );
        assert!(
            c.contains("CURLOPT_WRITEFUNCTION"),
            "missing CURLOPT_WRITEFUNCTION"
        );
        assert!(
            c.contains("CURLOPT_WRITEDATA"),
            "missing CURLOPT_WRITEDATA"
        );
    }
}
