use minijinja::{context, Environment};
use nexus_core::{Contract, Schema};

use crate::{header::to_pascal_case, CodegenError, GeneratedFile};

// ── template (embedded as const &str) ─────────────────────────────────────────

const IMPL_TMPL: &str = r#"/* Generated by nexus-gen — DO NOT EDIT */
#include "nexus_{{ contract_name }}.h"
#include <sys/mman.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

static void* _nexus_{{ contract_name }}_shm = NULL;
static int _nexus_{{ contract_name }}_fd = -1;

int nexus_{{ contract_name }}_init(void) {
    const char* name = getenv("NEXUS_{{ contract_name_upper }}_SHM");
    if (!name) name = "/nexus_{{ contract_name }}";

    _nexus_{{ contract_name }}_fd = shm_open(name, O_CREAT | O_RDWR, 0600);
    if (_nexus_{{ contract_name }}_fd < 0) return NEXUS_ERR_INIT;

    if (ftruncate(_nexus_{{ contract_name }}_fd, sizeof(Nexus{{ struct_name }})) < 0) {
        close(_nexus_{{ contract_name }}_fd);
        _nexus_{{ contract_name }}_fd = -1;
        return NEXUS_ERR_INIT;
    }

    _nexus_{{ contract_name }}_shm = mmap(
        NULL,
        sizeof(Nexus{{ struct_name }}),
        PROT_READ | PROT_WRITE,
        MAP_SHARED,
        _nexus_{{ contract_name }}_fd,
        0
    );
    if (_nexus_{{ contract_name }}_shm == MAP_FAILED) {
        close(_nexus_{{ contract_name }}_fd);
        _nexus_{{ contract_name }}_fd = -1;
        _nexus_{{ contract_name }}_shm = NULL;
        return NEXUS_ERR_INIT;
    }

    return NEXUS_OK;
}

void nexus_{{ contract_name }}_destroy(void) {
    if (_nexus_{{ contract_name }}_shm != NULL) {
        munmap(_nexus_{{ contract_name }}_shm, sizeof(Nexus{{ struct_name }}));
        _nexus_{{ contract_name }}_shm = NULL;
    }
    if (_nexus_{{ contract_name }}_fd >= 0) {
        const char* name = getenv("NEXUS_{{ contract_name_upper }}_SHM");
        if (!name) name = "/nexus_{{ contract_name }}";
        close(_nexus_{{ contract_name }}_fd);
        _nexus_{{ contract_name }}_fd = -1;
        shm_unlink(name);
    }
}

int nexus_send_{{ contract_name }}(const Nexus{{ struct_name }}* data) {
    if (_nexus_{{ contract_name }}_shm == NULL) return NEXUS_ERR_INIT;
    memcpy(_nexus_{{ contract_name }}_shm, data, sizeof(*data));
    return NEXUS_OK;
}

int nexus_recv_{{ contract_name }}(Nexus{{ struct_name }}* out) {
    if (_nexus_{{ contract_name }}_shm == NULL) return NEXUS_ERR_INIT;
    memcpy(out, _nexus_{{ contract_name }}_shm, sizeof(*out));
    return NEXUS_OK;
}
"#;

// ── public API ────────────────────────────────────────────────────────────────

/// Generate an iceoryx (POSIX shared memory stub) C implementation file for
/// the given contract.
pub fn generate_impl(contract: &Contract, schema: &Schema) -> Result<GeneratedFile, CodegenError> {
    let mut env = Environment::new();
    env.add_template("impl", IMPL_TMPL)?;
    let tmpl = env.get_template("impl")?;

    let contract_name_upper = contract.name.to_uppercase();
    let struct_name = schema.structs.last()
        .map(|s| to_pascal_case(&s.name))
        .unwrap_or_else(|| to_pascal_case(&contract.name));

    let rendered = tmpl.render(context! {
        contract_name => contract.name,
        contract_name_upper => contract_name_upper,
        struct_name => struct_name,
    })?;

    Ok(GeneratedFile {
        path: format!("src/nexus_{}.c", contract.name),
        content: rendered,
    })
}

// ── tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use nexus_core::{Contract, Schema, SchemaIdx, StructDef, Transport};

    use super::*;

    fn test_contract() -> (Contract, Schema) {
        let contract = Contract {
            name: "game_info".to_string(),
            transport: Transport::Iceoryx,
            schema: SchemaIdx(0),
        };
        let schema = Schema {
            name: "game_info".to_string(),
            structs: vec![StructDef {
                name: "game_info".to_string(),
                fields: vec![],
            }],
        };
        (contract, schema)
    }

    #[test]
    fn test_impl_generation() {
        let (contract, schema) = test_contract();
        let file = generate_impl(&contract, &schema).unwrap();

        assert_eq!(file.path, "src/nexus_game_info.c");

        let c = &file.content;

        // Includes
        assert!(
            c.contains("#include \"nexus_game_info.h\""),
            "missing own header include"
        );
        assert!(c.contains("#include <sys/mman.h>"), "missing mman include");
        assert!(c.contains("#include <sys/stat.h>"), "missing stat include");
        assert!(c.contains("#include <fcntl.h>"), "missing fcntl include");
        assert!(c.contains("#include <unistd.h>"), "missing unistd include");
        assert!(c.contains("#include <stdlib.h>"), "missing stdlib include");
        assert!(c.contains("#include <string.h>"), "missing string include");
        assert!(c.contains("#include <stdio.h>"), "missing stdio include");

        // Static variables
        assert!(
            c.contains("static void* _nexus_game_info_shm = NULL;"),
            "missing static shm pointer"
        );
        assert!(
            c.contains("static int _nexus_game_info_fd = -1;"),
            "missing static fd"
        );

        // Functions
        assert!(c.contains("nexus_game_info_init"), "missing init function");
        assert!(
            c.contains("nexus_game_info_destroy"),
            "missing destroy function"
        );
        assert!(c.contains("nexus_send_game_info"), "missing send function");
        assert!(c.contains("nexus_recv_game_info"), "missing recv function");

        // Struct name
        assert!(
            c.contains("NexusGameInfo"),
            "missing struct name in functions"
        );

        // Env var name
        assert!(
            c.contains("NEXUS_GAME_INFO_SHM"),
            "missing env var for shm name"
        );

        // Default shm name
        assert!(
            c.contains("/nexus_game_info"),
            "missing default shm name"
        );

        // shm_open usage (must use restrictive 0600 mode, not 0666)
        assert!(c.contains("shm_open("), "missing shm_open call");
        assert!(
            c.contains("O_CREAT | O_RDWR, 0600"),
            "shm_open must use mode 0600"
        );
        assert!(c.contains("ftruncate("), "missing ftruncate call");
        assert!(c.contains("mmap("), "missing mmap call");
        assert!(c.contains("munmap("), "missing munmap call");
        assert!(c.contains("shm_unlink("), "missing shm_unlink call");

        // Zero-copy memcpy usage
        assert!(
            c.contains("memcpy(_nexus_game_info_shm, data"),
            "missing send memcpy"
        );
        assert!(
            c.contains("memcpy(out, _nexus_game_info_shm"),
            "missing recv memcpy"
        );
    }
}
