use minijinja::{context, Environment};
use nexus_core::{Contract, Schema};

use crate::{header::to_pascal_case, CodegenError, GeneratedFile};

// ── template (embedded as const &str) ─────────────────────────────────────────

const SERVER_IMPL_TMPL: &str = r#"/* Generated by nexus-gen — DO NOT EDIT */
#include "nexus_{{ contract_name }}.h"
#include <string.h>
#include <stdlib.h>
#include <pthread.h>

/* Shared gRPC runtime (from nexus_grpc_runtime.c) */
extern int _nexus_grpc_start(const char* addr);
extern int _nexus_grpc_register(const char* method, const void* cache_ptr,
                                 size_t cache_size, pthread_mutex_t* mutex);
extern void _nexus_grpc_stop(void);

static Nexus{{ struct_name }} _nexus_{{ contract_name }}_cache;
static pthread_mutex_t _nexus_{{ contract_name }}_mutex = PTHREAD_MUTEX_INITIALIZER;

int nexus_{{ contract_name }}_init(void) {
    const char* addr = getenv("NEXUS_{{ contract_name_upper }}_ADDR");
    if (!addr) addr = "0.0.0.0:50052";

    memset(&_nexus_{{ contract_name }}_cache, 0, sizeof(_nexus_{{ contract_name }}_cache));

    if (_nexus_grpc_start(addr) != 0) return NEXUS_ERR_INIT;

    if (_nexus_grpc_register(
            "/nexus.{{ struct_name }}/Recv",
            &_nexus_{{ contract_name }}_cache,
            sizeof(_nexus_{{ contract_name }}_cache),
            &_nexus_{{ contract_name }}_mutex) < 0) {
        return NEXUS_ERR_INIT;
    }

    return NEXUS_OK;
}

void nexus_{{ contract_name }}_destroy(void) {
    _nexus_grpc_stop();
}

int nexus_send_{{ contract_name }}(const Nexus{{ struct_name }}* data) {
    pthread_mutex_lock(&_nexus_{{ contract_name }}_mutex);
    memcpy(&_nexus_{{ contract_name }}_cache, data, sizeof(*data));
    pthread_mutex_unlock(&_nexus_{{ contract_name }}_mutex);
    return NEXUS_OK;
}

int nexus_recv_{{ contract_name }}(Nexus{{ struct_name }}* out) {
    /* Server nodes do not receive on this contract */
    (void)out;
    return NEXUS_ERR_INIT;
}
"#;

// ── public API ────────────────────────────────────────────────────────────────

/// Generate a gRPC server-side C implementation file for the given contract.
/// The output delegates to the shared runtime from `nexus_grpc_runtime.c`.
/// The `schema` parameter is accepted for API symmetry but is not used
/// directly — all needed names are derived from the contract.
pub fn generate_impl(contract: &Contract, _schema: &Schema) -> Result<GeneratedFile, CodegenError> {
    let mut env = Environment::new();
    env.add_template("server_impl", SERVER_IMPL_TMPL)?;
    let tmpl = env.get_template("server_impl")?;

    let contract_name_upper = contract.name.to_uppercase();
    let struct_name = to_pascal_case(&contract.name);

    let rendered = tmpl.render(context! {
        contract_name => contract.name,
        contract_name_upper => contract_name_upper,
        struct_name => struct_name,
    })?;

    Ok(GeneratedFile {
        path: format!("src/nexus_{}_server.c", contract.name),
        content: rendered,
    })
}

// ── tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use nexus_core::{Contract, Schema, SchemaIdx, StructDef, Transport};

    use super::*;

    fn test_contract() -> (Contract, Schema) {
        let contract = Contract {
            name: "game_info".to_string(),
            transport: Transport::Grpc,
            schema: SchemaIdx(0),
        };
        let schema = Schema {
            name: "game_info".to_string(),
            structs: vec![StructDef {
                name: "game_info".to_string(),
                fields: vec![],
            }],
        };
        (contract, schema)
    }

    #[test]
    fn test_server_impl_generation() {
        let (contract, schema) = test_contract();
        let file = generate_impl(&contract, &schema).unwrap();
        assert_eq!(file.path, "src/nexus_game_info_server.c");
        assert!(file.content.contains("_nexus_grpc_start"));
        assert!(file.content.contains("_nexus_grpc_register"));
        assert!(file.content.contains("/nexus.GameInfo/Recv"));
        assert!(file.content.contains("nexus_send_game_info"));
        assert!(file.content.contains("pthread_mutex_lock"));
        assert!(file.content.contains("memcpy"));
    }
}
