use minijinja::{context, Environment};
use nexus_core::{Contract, Schema};

use crate::{header::to_pascal_case, CodegenError, GeneratedFile};

// ── template (embedded as const &str) ─────────────────────────────────────────

const IMPL_TMPL: &str = r#"/* Generated by nexus-gen — DO NOT EDIT */
#include "nexus_{{ contract_name }}.h"
#include <sys/socket.h>
#include <sys/un.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <stdio.h>

static int _nexus_{{ contract_name }}_fd = -1;

int nexus_{{ contract_name }}_init(void) {
    const char* addr = getenv("NEXUS_{{ contract_name_upper }}_ADDR");
    if (!addr) addr = "/tmp/nexus_{{ contract_name }}.sock";

    _nexus_{{ contract_name }}_fd = socket(AF_UNIX, SOCK_STREAM, 0);
    if (_nexus_{{ contract_name }}_fd < 0) return NEXUS_ERR_INIT;

    struct sockaddr_un sa;
    memset(&sa, 0, sizeof(sa));
    sa.sun_family = AF_UNIX;
    strncpy(sa.sun_path, addr, sizeof(sa.sun_path) - 1);

    if (connect(_nexus_{{ contract_name }}_fd, (struct sockaddr*)&sa, sizeof(sa)) < 0) {
        close(_nexus_{{ contract_name }}_fd);
        _nexus_{{ contract_name }}_fd = -1;
        return NEXUS_ERR_INIT;
    }

    return NEXUS_OK;
}

void nexus_{{ contract_name }}_destroy(void) {
    if (_nexus_{{ contract_name }}_fd >= 0) {
        close(_nexus_{{ contract_name }}_fd);
        _nexus_{{ contract_name }}_fd = -1;
    }
}

int nexus_send_{{ contract_name }}(const Nexus{{ struct_name }}* data) {
    if (_nexus_{{ contract_name }}_fd < 0) return NEXUS_ERR_INIT;
    ssize_t n = send(_nexus_{{ contract_name }}_fd, data, sizeof(*data), 0);
    if (n < 0) return NEXUS_ERR_CLOSED;
    return NEXUS_OK;
}

int nexus_recv_{{ contract_name }}(Nexus{{ struct_name }}* out) {
    if (_nexus_{{ contract_name }}_fd < 0) return NEXUS_ERR_INIT;
    ssize_t n = recv(_nexus_{{ contract_name }}_fd, out, sizeof(*out), MSG_WAITALL);
    if (n == 0) return NEXUS_ERR_CLOSED;
    if (n < 0) return NEXUS_ERR_CLOSED;
    return NEXUS_OK;
}
"#;

// ── public API ────────────────────────────────────────────────────────────────

/// Generate a Unix socket C implementation file for the given contract.
/// The `schema` parameter is accepted for API symmetry but is not used
/// directly — all needed names are derived from the contract.
pub fn generate_impl(contract: &Contract, _schema: &Schema) -> Result<GeneratedFile, CodegenError> {
    let mut env = Environment::new();
    env.add_template("impl", IMPL_TMPL)?;
    let tmpl = env.get_template("impl")?;

    let contract_name_upper = contract.name.to_uppercase();
    let struct_name = to_pascal_case(&contract.name);

    let rendered = tmpl.render(context! {
        contract_name => contract.name,
        contract_name_upper => contract_name_upper,
        struct_name => struct_name,
    })?;

    Ok(GeneratedFile {
        path: format!("src/nexus_{}.c", contract.name),
        content: rendered,
    })
}

// ── tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use nexus_core::{Contract, Schema, SchemaIdx, StructDef, Transport};

    use super::*;

    fn game_info_contract() -> (Contract, Schema) {
        let contract = Contract {
            name: "game_info".to_string(),
            transport: Transport::UnixSocket,
            schema: SchemaIdx(0),
        };
        let schema = Schema {
            name: "game_info".to_string(),
            structs: vec![StructDef {
                name: "game_info".to_string(),
                fields: vec![],
            }],
        };
        (contract, schema)
    }

    #[test]
    fn test_impl_generation() {
        let (contract, schema) = game_info_contract();
        let file = generate_impl(&contract, &schema).unwrap();

        assert_eq!(file.path, "src/nexus_game_info.c");

        let c = &file.content;
        // Includes
        assert!(
            c.contains("#include \"nexus_game_info.h\""),
            "missing own header include"
        );
        assert!(
            c.contains("#include <sys/socket.h>"),
            "missing socket include"
        );
        assert!(
            c.contains("#include <sys/un.h>"),
            "missing unix socket include"
        );
        assert!(c.contains("#include <unistd.h>"), "missing unistd include");

        // Static fd
        assert!(
            c.contains("static int _nexus_game_info_fd = -1;"),
            "missing static fd"
        );

        // Functions
        assert!(c.contains("nexus_game_info_init"), "missing init function");
        assert!(
            c.contains("nexus_game_info_destroy"),
            "missing destroy function"
        );
        assert!(c.contains("nexus_send_game_info"), "missing send function");
        assert!(c.contains("nexus_recv_game_info"), "missing recv function");

        // Struct name
        assert!(
            c.contains("NexusGameInfo"),
            "missing struct name in functions"
        );

        // Env var name
        assert!(c.contains("NEXUS_GAME_INFO_ADDR"), "missing env var");

        // Socket path default
        assert!(
            c.contains("/tmp/nexus_game_info.sock"),
            "missing default socket path"
        );
    }
}
