use minijinja::{context, Environment};
use nexus_core::{Contract, Schema};

use crate::{header::to_pascal_case, CodegenError, GeneratedFile};

// ── template (embedded as const &str) ─────────────────────────────────────────

const IMPL_TMPL: &str = r#"/* Generated by nexus-gen — DO NOT EDIT */
#include "nexus_{{ contract_name }}.h"
#include <grpc/grpc.h>
#include <grpc/credentials.h>
#include <grpc/byte_buffer.h>
#include <grpc/byte_buffer_reader.h>
#include <grpc/support/alloc.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

static grpc_channel* _nexus_{{ contract_name }}_channel = NULL;

int nexus_{{ contract_name }}_init(void) {
    const char* addr = getenv("NEXUS_{{ contract_name_upper }}_ADDR");
    if (!addr) addr = "localhost:50052";

    grpc_init();

    _nexus_{{ contract_name }}_channel = grpc_insecure_channel_create(addr, NULL, NULL);
    if (!_nexus_{{ contract_name }}_channel) return NEXUS_ERR_INIT;

    return NEXUS_OK;
}

void nexus_{{ contract_name }}_destroy(void) {
    if (_nexus_{{ contract_name }}_channel) {
        grpc_channel_destroy(_nexus_{{ contract_name }}_channel);
        _nexus_{{ contract_name }}_channel = NULL;
    }
    grpc_shutdown();
}

int nexus_send_{{ contract_name }}(const Nexus{{ struct_name }}* data) {
    if (!_nexus_{{ contract_name }}_channel) return NEXUS_ERR_INIT;

    grpc_slice slice = grpc_slice_from_copied_buffer((const char*)data, sizeof(*data));
    grpc_byte_buffer* send_buf = grpc_raw_byte_buffer_create(&slice, 1);
    grpc_slice_unref(slice);

    grpc_call* call = grpc_channel_create_call(
        _nexus_{{ contract_name }}_channel, NULL, GRPC_PROPAGATE_DEFAULTS,
        grpc_completion_queue_create_for_pluck(NULL),
        grpc_slice_from_static_string("/nexus.{{ struct_name }}/Send"),
        NULL, gpr_inf_future(GPR_CLOCK_REALTIME), NULL);
    if (!call) {
        grpc_byte_buffer_destroy(send_buf);
        return NEXUS_ERR_CLOSED;
    }

    grpc_op ops[1];
    memset(ops, 0, sizeof(ops));
    ops[0].op = GRPC_OP_SEND_MESSAGE;
    ops[0].data.send_message.send_message = send_buf;

    grpc_call_error err = grpc_call_start_batch(call, ops, 1, NULL, NULL);

    grpc_byte_buffer_destroy(send_buf);
    grpc_call_unref(call);

    if (err != GRPC_CALL_OK) return NEXUS_ERR_CLOSED;
    return NEXUS_OK;
}

int nexus_recv_{{ contract_name }}(Nexus{{ struct_name }}* out) {
    if (!_nexus_{{ contract_name }}_channel) return NEXUS_ERR_INIT;

    grpc_byte_buffer* recv_buf = NULL;

    grpc_call* call = grpc_channel_create_call(
        _nexus_{{ contract_name }}_channel, NULL, GRPC_PROPAGATE_DEFAULTS,
        grpc_completion_queue_create_for_pluck(NULL),
        grpc_slice_from_static_string("/nexus.{{ struct_name }}/Recv"),
        NULL, gpr_inf_future(GPR_CLOCK_REALTIME), NULL);
    if (!call) return NEXUS_ERR_CLOSED;

    grpc_op ops[1];
    memset(ops, 0, sizeof(ops));
    ops[0].op = GRPC_OP_RECV_MESSAGE;
    ops[0].data.recv_message.recv_message = &recv_buf;

    grpc_call_error err = grpc_call_start_batch(call, ops, 1, NULL, NULL);
    if (err != GRPC_CALL_OK) {
        grpc_call_unref(call);
        return NEXUS_ERR_CLOSED;
    }

    if (!recv_buf) {
        grpc_call_unref(call);
        return NEXUS_ERR_CLOSED;
    }

    grpc_byte_buffer_reader reader;
    grpc_byte_buffer_reader_init(&reader, recv_buf);
    grpc_slice result = grpc_byte_buffer_reader_readall(&reader);
    grpc_byte_buffer_reader_destroy(&reader);

    size_t len = GRPC_SLICE_LENGTH(result);
    if (len >= sizeof(*out)) {
        memcpy(out, GRPC_SLICE_START_PTR(result), sizeof(*out));
    }
    grpc_slice_unref(result);

    grpc_byte_buffer_destroy(recv_buf);
    grpc_call_unref(call);

    if (len < sizeof(*out)) return NEXUS_ERR_CLOSED;
    return NEXUS_OK;
}
"#;

// ── public API ────────────────────────────────────────────────────────────────

/// Generate a gRPC C implementation file for the given contract.
pub fn generate_impl(contract: &Contract, schema: &Schema) -> Result<GeneratedFile, CodegenError> {
    let mut env = Environment::new();
    env.add_template("impl", IMPL_TMPL)?;
    let tmpl = env.get_template("impl")?;

    let contract_name_upper = contract.name.to_uppercase();
    let struct_name = schema.structs.last()
        .map(|s| to_pascal_case(&s.name))
        .unwrap_or_else(|| to_pascal_case(&contract.name));

    let rendered = tmpl.render(context! {
        contract_name => contract.name,
        contract_name_upper => contract_name_upper,
        struct_name => struct_name,
    })?;

    Ok(GeneratedFile {
        path: format!("src/nexus_{}.c", contract.name),
        content: rendered,
    })
}

// ── tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use nexus_core::{Contract, Schema, SchemaIdx, StructDef, Transport};

    use super::*;

    fn test_contract() -> (Contract, Schema) {
        let contract = Contract {
            name: "game_info".to_string(),
            transport: Transport::Grpc,
            schema: SchemaIdx(0),
        };
        let schema = Schema {
            name: "game_info".to_string(),
            structs: vec![StructDef {
                name: "game_info".to_string(),
                fields: vec![],
            }],
        };
        (contract, schema)
    }

    #[test]
    fn test_impl_generation() {
        let (contract, schema) = test_contract();
        let file = generate_impl(&contract, &schema).unwrap();

        assert_eq!(file.path, "src/nexus_game_info.c");

        let c = &file.content;

        // Includes
        assert!(
            c.contains("#include \"nexus_game_info.h\""),
            "missing own header include"
        );
        assert!(
            c.contains("#include <grpc/grpc.h>"),
            "missing grpc include"
        );
        assert!(
            c.contains("#include <grpc/byte_buffer.h>"),
            "missing grpc byte_buffer include"
        );
        assert!(
            c.contains("#include <grpc/support/alloc.h>"),
            "missing grpc alloc include"
        );
        assert!(c.contains("#include <stdlib.h>"), "missing stdlib include");
        assert!(c.contains("#include <string.h>"), "missing string include");
        assert!(c.contains("#include <stdio.h>"), "missing stdio include");

        // Static channel
        assert!(
            c.contains("static grpc_channel* _nexus_game_info_channel = NULL;"),
            "missing static channel"
        );

        // Functions
        assert!(c.contains("nexus_game_info_init"), "missing init function");
        assert!(
            c.contains("nexus_game_info_destroy"),
            "missing destroy function"
        );
        assert!(c.contains("nexus_send_game_info"), "missing send function");
        assert!(c.contains("nexus_recv_game_info"), "missing recv function");

        // Struct name
        assert!(
            c.contains("NexusGameInfo"),
            "missing struct name in functions"
        );

        // Env var name
        assert!(c.contains("NEXUS_GAME_INFO_ADDR"), "missing env var");

        // Default gRPC address
        assert!(
            c.contains("localhost:50052"),
            "missing default grpc address"
        );

        // gRPC method paths
        assert!(
            c.contains("/nexus.GameInfo/Send"),
            "missing grpc Send method path"
        );
        assert!(
            c.contains("/nexus.GameInfo/Recv"),
            "missing grpc Recv method path"
        );
    }
}
