use minijinja::{context, Environment};
use nexus_core::{Contract, FieldType, Schema, StructDef};

use crate::{header::to_pascal_case, CodegenError, GeneratedFile};

// ── template (embedded as const &str) ─────────────────────────────────────────

const IMPL_TMPL: &str = r#"/* Generated by nexus-gen — DO NOT EDIT */
#include "nexus_{{ contract_name }}.h"
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <pthread.h>

/* Shared HTTP runtime (from nexus_http_runtime.c) */
typedef char* (*_nexus_json_fn)(const void* data);
extern int _nexus_http_start(int port);
extern int _nexus_http_register(const char* path, const void* cache_ptr,
                                 pthread_mutex_t* mutex, _nexus_json_fn to_json);
extern void _nexus_http_stop(void);

static Nexus{{ struct_name }} _nexus_{{ contract_name }}_cache;
static pthread_mutex_t _nexus_{{ contract_name }}_mutex = PTHREAD_MUTEX_INITIALIZER;

{{ json_fn }}

int nexus_{{ contract_name }}_init(void) {
    const char* addr = getenv("NEXUS_{{ contract_name_upper }}_ADDR");
    int port = 8080;
    if (addr) {
        /* Parse port from URL like "http://0.0.0.0:8080/nexus/..." or just "8080" */
        const char* colon = strrchr(addr, ':');
        if (colon) {
            int p = atoi(colon + 1);
            if (p > 0) port = p;
        }
    }

    memset(&_nexus_{{ contract_name }}_cache, 0, sizeof(_nexus_{{ contract_name }}_cache));

    if (_nexus_http_start(port) != 0) return NEXUS_ERR_INIT;

    if (_nexus_http_register(
            "/nexus/{{ contract_name }}",
            &_nexus_{{ contract_name }}_cache,
            &_nexus_{{ contract_name }}_mutex,
            _nexus_{{ contract_name }}_to_json) < 0) {
        return NEXUS_ERR_INIT;
    }

    return NEXUS_OK;
}

void nexus_{{ contract_name }}_destroy(void) {
    _nexus_http_stop();
}

int nexus_send_{{ contract_name }}(const Nexus{{ struct_name }}* data) {
    pthread_mutex_lock(&_nexus_{{ contract_name }}_mutex);
    memcpy(&_nexus_{{ contract_name }}_cache, data, sizeof(*data));
    pthread_mutex_unlock(&_nexus_{{ contract_name }}_mutex);
    return NEXUS_OK;
}

int nexus_recv_{{ contract_name }}(Nexus{{ struct_name }}* out) {
    /* Server nodes do not receive on this contract */
    (void)out;
    return NEXUS_ERR_INIT;
}
"#;

// ── JSON serializer generator ─────────────────────────────────────────────────

/// Returns (format_spec, arg_expr) for a single primitive field.
fn field_fmt(typ: &FieldType, access: &str) -> (String, String) {
    match typ {
        FieldType::U8 | FieldType::U16 | FieldType::U32 => {
            ("%u".into(), format!("(unsigned){access}"))
        }
        FieldType::U64 => ("%llu".into(), format!("(unsigned long long){access}")),
        FieldType::I8 | FieldType::I16 | FieldType::I32 => ("%d".into(), access.to_string()),
        FieldType::I64 => ("%lld".into(), format!("(long long){access}")),
        FieldType::F32 | FieldType::F64 => ("%.6g".into(), access.to_string()),
        FieldType::Bool => ("%s".into(), format!("({access} ? \"true\" : \"false\")")),
        FieldType::StringFixed(_) => ("\\\"%s\\\"".into(), access.to_string()),
        FieldType::Bytes(_) => ("\\\"%s\\\"".into(), format!("\"<bytes>\"")),
        FieldType::Array { .. } => ("\"[]\": skipped".into(), "".to_string()),
        FieldType::Nested(_) => ("\"{}\"".into(), "".to_string()),
    }
}

/// Estimate a safe JSON buffer size for the struct.
fn buf_size(s: &StructDef) -> usize {
    let per_field = 64usize; // name + colon + max value + comma
    (s.fields.len() * per_field + 64).max(256)
}

/// Generate the `_nexus_<contract>_to_json(const void*)` C function.
fn generate_json_fn(contract_name: &str, struct_name: &str, schema: &Schema) -> String {
    let s = schema
        .structs
        .iter()
        .find(|s| to_pascal_case(&s.name) == struct_name)
        .or_else(|| schema.structs.last());

    let Some(s) = s else {
        return format!(
            "static char* _nexus_{contract_name}_to_json(const void* data) {{\n\
             \t(void)data;\n\
             \tchar* buf = malloc(3);\n\
             \tif (!buf) return NULL;\n\
             \tsnprintf(buf, 3, \"{{}}\");\n\
             \treturn buf;\n\
             }}"
        );
    };

    let size = buf_size(s);
    let d = format!("((const Nexus{struct_name}*)data)");

    // Build the snprintf format string and argument list field-by-field.
    // Skip Array and Nested for now — they render as null.
    let mut parts: Vec<String> = Vec::new();
    let mut args: Vec<String> = Vec::new();

    for field in &s.fields {
        let access = format!("{d}->{}", field.name);
        match &field.typ {
            FieldType::Array { .. } | FieldType::Nested(_) => {
                parts.push(format!("\\\"{}\\\":null", field.name));
            }
            typ => {
                let (fmt, arg) = field_fmt(typ, &access);
                parts.push(format!("\\\"{}\\\":{fmt}", field.name));
                if !arg.is_empty() {
                    args.push(arg);
                }
            }
        }
    }

    let fmt_body = parts.join(",");
    let args_str = if args.is_empty() {
        String::new()
    } else {
        format!(", {}", args.join(", "))
    };

    format!(
        "static char* _nexus_{contract_name}_to_json(const void* data) {{\n\
         \tchar* buf = malloc({size});\n\
         \tif (!buf) return NULL;\n\
         \tsnprintf(buf, {size}, \"{{{fmt_body}}}\"{args_str});\n\
         \treturn buf;\n\
         }}"
    )
}

// ── public API ────────────────────────────────────────────────────────────────

/// Generate a per-contract HTTP server handler with JSON serialization.
pub fn generate_impl(contract: &Contract, schema: &Schema) -> Result<GeneratedFile, CodegenError> {
    let mut env = Environment::new();
    env.add_template("impl", IMPL_TMPL)?;
    let tmpl = env.get_template("impl")?;

    let contract_name_upper = contract.name.to_uppercase();
    let struct_name = schema
        .structs
        .last()
        .map(|s| to_pascal_case(&s.name))
        .unwrap_or_else(|| to_pascal_case(&contract.name));

    let json_fn = generate_json_fn(&contract.name, &struct_name, schema);

    let rendered = tmpl.render(context! {
        contract_name => contract.name,
        contract_name_upper => contract_name_upper,
        struct_name => struct_name,
        json_fn => json_fn,
    })?;

    Ok(GeneratedFile {
        path: format!("src/nexus_{}_server.c", contract.name),
        content: rendered,
    })
}

// ── tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use nexus_core::{Field, FieldType, SchemaIdx, StructDef, Transport};

    use super::*;

    fn test_contract() -> (Contract, Schema) {
        let contract = Contract {
            name: "game_info".to_string(),
            transport: Transport::Http,
            schema: SchemaIdx(0),
        };
        let schema = Schema {
            name: "game_info".to_string(),
            structs: vec![StructDef {
                name: "game_info".to_string(),
                fields: vec![
                    Field { name: "score".to_string(), typ: FieldType::U32 },
                    Field { name: "elapsed".to_string(), typ: FieldType::F64 },
                    Field { name: "active".to_string(), typ: FieldType::Bool },
                ],
            }],
        };
        (contract, schema)
    }

    #[test]
    fn test_server_impl_generation() {
        let (contract, schema) = test_contract();
        let file = generate_impl(&contract, &schema).unwrap();
        assert_eq!(file.path, "src/nexus_game_info_server.c");
        assert!(file.content.contains("_nexus_http_start"));
        assert!(file.content.contains("_nexus_http_register"));
        assert!(file.content.contains("/nexus/game_info"));
        assert!(file.content.contains("nexus_send_game_info"));
        assert!(file.content.contains("pthread_mutex_lock"));
    }

    #[test]
    fn test_json_fn_primitives() {
        let (contract, schema) = test_contract();
        let file = generate_impl(&contract, &schema).unwrap();
        assert!(file.content.contains("_nexus_game_info_to_json"));
        assert!(file.content.contains(r#"\"score\""#));
        assert!(file.content.contains(r#"\"elapsed\""#));
        assert!(file.content.contains(r#"\"active\""#));
        assert!(file.content.contains("snprintf"));
        assert!(file.content.contains("to_json"));
    }

    #[test]
    fn test_json_fn_u64_cast() {
        let contract = Contract {
            name: "mem_info".to_string(),
            transport: Transport::Http,
            schema: SchemaIdx(0),
        };
        let schema = Schema {
            name: "mem_info".to_string(),
            structs: vec![StructDef {
                name: "mem_info".to_string(),
                fields: vec![
                    Field { name: "total_bytes".to_string(), typ: FieldType::U64 },
                ],
            }],
        };
        let file = generate_impl(&contract, &schema).unwrap();
        assert!(file.content.contains("unsigned long long"));
        assert!(file.content.contains("%llu"));
    }
}
