use minijinja::{context, Environment, Value};
use nexus_core::{Contract, FieldType, Schema, StructDef};

use crate::{header::to_pascal_case, CodegenError, GeneratedFile};

// ── template (embedded as const &str) ─────────────────────────────────────────

const TS_TMPL: &str = r#"/* Generated by nexus-gen — DO NOT EDIT */

{% for iface in interfaces %}
export interface Nexus{{ iface.name }} {
{% for field in iface.fields %}
  {{ field.name }}: {{ field.ts_type }};
{% endfor %}
}
{% endfor %}

const NEXUS_{{ contract_name_upper }}_ADDR =
  import.meta.env.VITE_NEXUS_{{ contract_name_upper }}_ADDR ??
  "http://localhost:8080/nexus/{{ contract_name }}";

export async function nexusSend{{ struct_name }}(data: Nexus{{ struct_name }}): Promise<void> {
  await fetch(NEXUS_{{ contract_name_upper }}_ADDR, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(data),
  });
}

export async function nexusRecv{{ struct_name }}(): Promise<Nexus{{ struct_name }}> {
  const response = await fetch(NEXUS_{{ contract_name_upper }}_ADDR);
  return response.json() as Promise<Nexus{{ struct_name }}>;
}
"#;

// ── public API ────────────────────────────────────────────────────────────────

/// Generate a TypeScript file with interfaces and fetch-based send/recv
/// functions for the given contract.
pub fn generate_typescript(
    contract: &Contract,
    schema: &Schema,
) -> Result<GeneratedFile, CodegenError> {
    let mut env = Environment::new();
    env.add_template("typescript", TS_TMPL)?;
    let tmpl = env.get_template("typescript")?;

    let contract_name_upper = contract.name.to_uppercase();
    let struct_name = schema.structs.last()
        .map(|s| to_pascal_case(&s.name))
        .unwrap_or_else(|| to_pascal_case(&contract.name));

    let interfaces: Vec<Value> = schema.structs.iter().map(struct_to_value).collect();

    let rendered = tmpl.render(context! {
        contract_name => contract.name,
        contract_name_upper => contract_name_upper,
        struct_name => struct_name,
        interfaces => interfaces,
    })?;

    Ok(GeneratedFile {
        path: format!("ts/nexus_{}.ts", contract.name),
        content: rendered,
    })
}

// ── helpers ───────────────────────────────────────────────────────────────────

/// Map a FieldType to its TypeScript type string.
pub fn field_type_to_ts(typ: &FieldType) -> String {
    match typ {
        FieldType::U8
        | FieldType::U16
        | FieldType::U32
        | FieldType::I8
        | FieldType::I16
        | FieldType::I32
        | FieldType::F32
        | FieldType::F64 => "number".to_string(),

        FieldType::U64 | FieldType::I64 => "bigint".to_string(),

        FieldType::Bool => "boolean".to_string(),

        FieldType::StringFixed(_) => "string".to_string(),

        FieldType::Bytes(_) => "Uint8Array".to_string(),

        FieldType::Array { elem, .. } => format!("Array<{}>", field_type_to_ts(elem)),

        FieldType::Nested(name) => format!("Nexus{}", to_pascal_case(name)),
    }
}

/// Build a minijinja Value for a StructDef:
/// `{ name: PascalName, fields: [{name, ts_type}] }`.
fn struct_to_value(s: &StructDef) -> Value {
    let name = to_pascal_case(&s.name);
    let fields: Vec<Value> = s
        .fields
        .iter()
        .map(|f| {
            context! {
                name => f.name,
                ts_type => field_type_to_ts(&f.typ),
            }
        })
        .collect();

    context! {
        name => name,
        fields => fields,
    }
}

// ── tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use nexus_core::{Contract, Field, FieldType, Schema, SchemaIdx, StructDef, Transport};

    use super::*;

    fn game_info_contract() -> (Contract, Schema) {
        let contract = Contract {
            name: "game_info".to_string(),
            transport: Transport::UnixSocket,
            schema: SchemaIdx(0),
        };
        let schema = Schema {
            name: "game_info".to_string(),
            structs: vec![StructDef {
                name: "game_info".to_string(),
                fields: vec![
                    Field {
                        name: "player_id".to_string(),
                        typ: FieldType::U32,
                    },
                    Field {
                        name: "score".to_string(),
                        typ: FieldType::I64,
                    },
                    Field {
                        name: "active".to_string(),
                        typ: FieldType::Bool,
                    },
                    Field {
                        name: "label".to_string(),
                        typ: FieldType::StringFixed(32),
                    },
                    Field {
                        name: "payload".to_string(),
                        typ: FieldType::Bytes(16),
                    },
                ],
            }],
        };
        (contract, schema)
    }

    #[test]
    fn test_typescript_generation() {
        let (contract, schema) = game_info_contract();
        let file = generate_typescript(&contract, &schema).unwrap();

        assert_eq!(file.path, "ts/nexus_game_info.ts");

        let c = &file.content;

        // Banner
        assert!(
            c.contains("/* Generated by nexus-gen — DO NOT EDIT */"),
            "missing banner"
        );

        // Interface
        assert!(
            c.contains("export interface NexusGameInfo"),
            "missing interface"
        );
        assert!(c.contains("player_id: number"), "missing player_id field");
        assert!(c.contains("score: bigint"), "missing score field");
        assert!(c.contains("active: boolean"), "missing active field");
        assert!(c.contains("label: string"), "missing label field");
        assert!(c.contains("payload: Uint8Array"), "missing payload field");

        // Env var address constant
        assert!(
            c.contains("VITE_NEXUS_GAME_INFO_ADDR"),
            "missing VITE env var"
        );
        assert!(
            c.contains("http://localhost:8080/nexus/game_info"),
            "missing default URL"
        );

        // Send function
        assert!(
            c.contains("export async function nexusSendGameInfo(data: NexusGameInfo): Promise<void>"),
            "missing send function signature"
        );
        assert!(c.contains("method: \"POST\""), "missing POST method");
        assert!(
            c.contains("JSON.stringify(data)"),
            "missing JSON.stringify call"
        );

        // Recv function
        assert!(
            c.contains(
                "export async function nexusRecvGameInfo(): Promise<NexusGameInfo>"
            ),
            "missing recv function signature"
        );
        assert!(c.contains("response.json()"), "missing response.json call");
    }

    #[test]
    fn test_typescript_generation_nested_struct() {
        let contract = Contract {
            name: "player_state".to_string(),
            transport: Transport::UnixSocket,
            schema: SchemaIdx(0),
        };
        let schema = Schema {
            name: "player_state".to_string(),
            structs: vec![
                StructDef {
                    name: "vector2".to_string(),
                    fields: vec![
                        Field {
                            name: "x".to_string(),
                            typ: FieldType::F32,
                        },
                        Field {
                            name: "y".to_string(),
                            typ: FieldType::F32,
                        },
                    ],
                },
                StructDef {
                    name: "player_state".to_string(),
                    fields: vec![
                        Field {
                            name: "pos".to_string(),
                            typ: FieldType::Nested("vector2".to_string()),
                        },
                        Field {
                            name: "health".to_string(),
                            typ: FieldType::U32,
                        },
                    ],
                },
            ],
        };

        let file = generate_typescript(&contract, &schema).unwrap();
        let c = &file.content;

        // Both interfaces present
        assert!(c.contains("export interface NexusVector2"), "missing NexusVector2 interface");
        assert!(c.contains("export interface NexusPlayerState"), "missing NexusPlayerState interface");

        // Nested type reference
        assert!(c.contains("pos: NexusVector2"), "missing nested field type");

        // NexusVector2 definition must precede NexusPlayerState definition
        let pos_v2 = c.find("NexusVector2 {").expect("NexusVector2 block missing");
        let pos_ps = c
            .find("NexusPlayerState {")
            .expect("NexusPlayerState block missing");
        assert!(
            pos_v2 < pos_ps,
            "nested interface must appear before parent interface"
        );
    }

    #[test]
    fn test_field_type_mapping() {
        // number variants
        assert_eq!(field_type_to_ts(&FieldType::U8), "number");
        assert_eq!(field_type_to_ts(&FieldType::U16), "number");
        assert_eq!(field_type_to_ts(&FieldType::U32), "number");
        assert_eq!(field_type_to_ts(&FieldType::I8), "number");
        assert_eq!(field_type_to_ts(&FieldType::I16), "number");
        assert_eq!(field_type_to_ts(&FieldType::I32), "number");
        assert_eq!(field_type_to_ts(&FieldType::F32), "number");
        assert_eq!(field_type_to_ts(&FieldType::F64), "number");

        // bigint variants
        assert_eq!(field_type_to_ts(&FieldType::U64), "bigint");
        assert_eq!(field_type_to_ts(&FieldType::I64), "bigint");

        // boolean
        assert_eq!(field_type_to_ts(&FieldType::Bool), "boolean");

        // string
        assert_eq!(field_type_to_ts(&FieldType::StringFixed(64)), "string");

        // Uint8Array
        assert_eq!(field_type_to_ts(&FieldType::Bytes(8)), "Uint8Array");

        // Arrays
        assert_eq!(
            field_type_to_ts(&FieldType::Array {
                elem: Box::new(FieldType::U32),
                len: 4,
            }),
            "Array<number>"
        );
        assert_eq!(
            field_type_to_ts(&FieldType::Array {
                elem: Box::new(FieldType::U64),
                len: 2,
            }),
            "Array<bigint>"
        );
        // Nested array
        assert_eq!(
            field_type_to_ts(&FieldType::Array {
                elem: Box::new(FieldType::Array {
                    elem: Box::new(FieldType::F32),
                    len: 3,
                }),
                len: 2,
            }),
            "Array<Array<number>>"
        );

        // Nested struct reference
        assert_eq!(
            field_type_to_ts(&FieldType::Nested("my_type".to_string())),
            "NexusMyType"
        );
        assert_eq!(
            field_type_to_ts(&FieldType::Nested("vector2".to_string())),
            "NexusVector2"
        );
    }
}
